# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Marco De Benedictis Homepage
email: marcoxdebenedictis@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal web page of Marco De Benedictis, Security Researcher based in Italy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: myfearisnaked
github_username:  mrcdb

# Build settings
markdown: kramdown
# Disable this line when pushing to Github Pages
# theme: plainwhite
remote_theme: thelehhman/plainwhite-jekyll

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# plainwhite theme config
plainwhite:
  name: Marco De Benedictis
  tagline: IT Security Researcher
  date_format: "%b %-d, %Y"
  social_links:
    github: mrcdb
    linkedIn: in/marcoxdebenedictis
    twitter: myfearisnaked
  sitemap:  true
  show_excerpts: true
  analytics_id: UA-142193392-1
